my:
  name: Birgit
  age: 29
  mail: mail@example.com

server:
  port: 8080
springdoc:
  api-docs:
    enabled:
      true
spring:
  datasource:
    url: jdbc:h2:./bookshelf;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    username: birgit
    password: geheim
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    open-in-view: false

    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate

  sql:
    init:
      mode: always
  security:
    user:
      password: geheim
